### ISSUE TITLE
Support for commented code

### ISSUE THREAD

**Issue by aghasemi** [remykarem/python2jupyter#2]
It would be (even more) great if onw could kind of differentiate etween ordinary comment, which should become a markdown cell, and commented code, which shouldn't.

**Comment by raibosome** [comment]
Hi @aghasemi, am I right to say you are referring to code like below

```python
# model.fit()
model.eval()
model.inference()
```

which will in turn render the notebook as

![image](https://user-images.githubusercontent.com/11023859/55682648-c8180900-5968-11e9-8446-e0562fad04ea.png)

**Comment by aghasemi** [comment]
Yes. Exactly.

**Comment by raibosome** [comment]
Understand where you are coming from. If a paragraph starts with a comment, it will automatically be a markdown cell. To get the commented code to be rendered as code, you could move the commented code at the end of the paragraph like so

```
model.eval()
model.inference()
# model.fit()
```

and it will render the entire block as a code cell. 

I don’t have any ideas for your feature request. But you could suggest some :) Do keep in mind that we should aim for minimal code intervention.

**Comment by aghasemi** [comment]
One idea would be to use a certain starting sequence, such as #! =, for identifying (real) Markdown cells. One can add a command-line switch for this case so that we have the "basic" case as default for many people who use that.

**Comment by remykarem** [comment]
Thanks for the idea. I suggest that instead of acting on real Markdown cells, we can impose a simpler sequence `##` for commented code.

**Comment by remykarem** [comment]
Fixed in https://github.com/remykarem/python2jupyter/blob/fa7bac1be7be80ab7ee371181c8d373fabaf1cc2/p2j/p2j.py#L73

**Comment by jpmorris** [comment]
IMHO the design might be approaching things not 'syntactically' enough.  Jupyter, VSCode, Spyder, Pycharm, are all using cell delimiters.  The ambiguity described here probably occurs more often than just the comment/markdown ambiguity.  Moreover this certainly breaks compatability with the tools above.  I don't know if anyone is getting this right (esp Jupyter) but this should support cell delimiters for both stricter syntax and for compatibility purposes.
