### ISSUE TITLE
New feature : Jupyter to python

### ISSUE THREAD

**Issue by arita37** [remykarem/python2jupyter#4]
Few questions :
    Is it way to reuse your codebase for reverse operation ?
Jupyter to structured python files, using #Tag

#! preprocess.py:start:#details
.... jupyter cells
#! preprocess.py:end

#! train.py:start:#run the training
.... jupyter cells
#! train.py:end

So, we can have directly structured code using simple tags in the jupyter ?

**Comment by remykarem** [comment]
Hi @arita37, I don’t have plans for that currently as the jupyter library can already do that:

`jupyter nbconvert --to script mynotebook.ipynb`

**Comment by wilsonify** [comment]
any plan to treat the comments generated by nbconvert as explicit cell dividers?  

e.g.

```
# In[24]:
```
