### ISSUE TITLE
Prevent cutting beginning of comment

### ISSUE THREAD

**Issue by kpym** [remykarem/python2jupyter#5]
Badly written comments that do not have space after `#` are cut.
For example:
```python
#Test
```
becomes a markdown cell
```
est
```

**Comment by remykarem** [comment]
Fixed in 538501c.

**Comment by kpym** [comment]
It was ixed in 10739ccee349ed8163eaeaa8c76aae16d360c414, not in 538501c50f9326312cccbf8cbe74c0f0347069c9.
Thanks !
